upstream web_backend {
    server web:5000;
}
upstream api_backend {
    server api:5001;
}

server {
    listen 80;
    location /payment {
        root /usr/share/nginx/html;
        try_files /payment.html =404;
    }
    location / {
        proxy_pass http://web_backend;
    }
    location /api/ {
        proxy_pass http://api_backend/;
    }
}